### ISSUE TITLE
No install.sh script?

### ISSUE THREAD

**Issue by nimaafraz** [medianetlab/katana-slice_manager#47]
The first step for installation seems to be running the install.sh script but I can't find it in the repo.

**Comment by nimaafraz** [comment]
Ok I found it it's in the release A branch.

**Comment by themisAnagno** [comment]
Hi @nimaafraz, on the latest release you can just use the `start.sh` script and it will pull all necessary images from Docker hub registry. Sorry for that, I will update the instructions asap.
