### ISSUE TITLE
Interface for Free5GC 

### ISSUE THREAD

**Issue by minziran** [medianetlab/katana-slice_manager#57]
I try to integrate Katana with Free5GC. I don't know if there any interfaces I can use to combine theses two things.

Thank you in advance!

**Comment by themisAnagno** [comment]
Hello @minziran, Free5GC is currently not supported by Katana. This can be added to a future release.

You can contribute and develop the necessary interface if you want. You will need to create a new AN function for supporting the Free5GC services, and an EMS for managing these services.
